//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.28 at 05:06:42 PM CEST 
//


package org.omg.spec.bpmn._20100524.model;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import org.camunda.schema.zeebe._1.Properties;
import org.omg.spec.bpmn._20100524.di.BPMNDiagram;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="process">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;choice maxOccurs="unbounded">
 *                     &lt;element name="extensionElements" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                     &lt;element name="startEvent">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="outgoing" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;/sequence>
 *                             &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                             &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="task">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="extensionElements">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;sequence>
 *                                         &lt;element ref="{http://camunda.org/schema/zeebe/1.0}properties"/>
 *                                       &lt;/sequence>
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                               &lt;element name="incoming" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                               &lt;element name="outgoing" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                             &lt;/sequence>
 *                             &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                             &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="sequenceFlow">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="extensionElements">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;sequence minOccurs="0">
 *                                         &lt;element ref="{http://camunda.org/schema/zeebe/1.0}properties"/>
 *                                       &lt;/sequence>
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                             &lt;/sequence>
 *                             &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                             &lt;attribute name="sourceRef" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                             &lt;attribute name="targetRef" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                             &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="isExecutable" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.omg.org/spec/BPMN/20100524/DI}BPMNDiagram"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="targetNamespace" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="exporter" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="exporterVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "process",
    "bpmnDiagram"
})
@XmlRootElement(name = "definitions")
public class Definitions {

    @XmlElement(required = true)
    protected Definitions.Process process;
    @XmlElement(name = "BPMNDiagram", namespace = "http://www.omg.org/spec/BPMN/20100524/DI", required = true)
    protected BPMNDiagram bpmnDiagram;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "targetNamespace", required = true)
    protected String targetNamespace;
    @XmlAttribute(name = "exporter", required = true)
    protected String exporter;
    @XmlAttribute(name = "exporterVersion", required = true)
    protected String exporterVersion;

    /**
     * Gets the value of the process property.
     * 
     * @return
     *     possible object is
     *     {@link Definitions.Process }
     *     
     */
    public Definitions.Process getProcess() {
        return process;
    }

    /**
     * Sets the value of the process property.
     * 
     * @param value
     *     allowed object is
     *     {@link Definitions.Process }
     *     
     */
    public void setProcess(Definitions.Process value) {
        this.process = value;
    }

    /**
     * Gets the value of the bpmnDiagram property.
     * 
     * @return
     *     possible object is
     *     {@link BPMNDiagram }
     *     
     */
    public BPMNDiagram getBPMNDiagram() {
        return bpmnDiagram;
    }

    /**
     * Sets the value of the bpmnDiagram property.
     * 
     * @param value
     *     allowed object is
     *     {@link BPMNDiagram }
     *     
     */
    public void setBPMNDiagram(BPMNDiagram value) {
        this.bpmnDiagram = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the targetNamespace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetNamespace() {
        return targetNamespace;
    }

    /**
     * Sets the value of the targetNamespace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetNamespace(String value) {
        this.targetNamespace = value;
    }

    /**
     * Gets the value of the exporter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExporter() {
        return exporter;
    }

    /**
     * Sets the value of the exporter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExporter(String value) {
        this.exporter = value;
    }

    /**
     * Gets the value of the exporterVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExporterVersion() {
        return exporterVersion;
    }

    /**
     * Sets the value of the exporterVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExporterVersion(String value) {
        this.exporterVersion = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice maxOccurs="unbounded">
     *           &lt;element name="extensionElements" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *           &lt;element name="startEvent">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;sequence>
     *                     &lt;element name="outgoing" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;/sequence>
     *                   &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                   &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *           &lt;element name="task">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;sequence>
     *                     &lt;element name="extensionElements">
     *                       &lt;complexType>
     *                         &lt;complexContent>
     *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                             &lt;sequence>
     *                               &lt;element ref="{http://camunda.org/schema/zeebe/1.0}properties"/>
     *                             &lt;/sequence>
     *                           &lt;/restriction>
     *                         &lt;/complexContent>
     *                       &lt;/complexType>
     *                     &lt;/element>
     *                     &lt;element name="incoming" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                     &lt;element name="outgoing" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                   &lt;/sequence>
     *                   &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                   &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *           &lt;element name="sequenceFlow">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;sequence>
     *                     &lt;element name="extensionElements">
     *                       &lt;complexType>
     *                         &lt;complexContent>
     *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                             &lt;sequence minOccurs="0">
     *                               &lt;element ref="{http://camunda.org/schema/zeebe/1.0}properties"/>
     *                             &lt;/sequence>
     *                           &lt;/restriction>
     *                         &lt;/complexContent>
     *                       &lt;/complexType>
     *                     &lt;/element>
     *                   &lt;/sequence>
     *                   &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                   &lt;attribute name="sourceRef" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                   &lt;attribute name="targetRef" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                   &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *         &lt;/choice>
     *       &lt;/sequence>
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="isExecutable" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "extensionElementsOrStartEventOrTask"
    })
    public static class Process {

        @XmlElements({
            @XmlElement(name = "extensionElements"),
            @XmlElement(name = "startEvent", type = Definitions.Process.StartEvent.class),
            @XmlElement(name = "task", type = Definitions.Process.Task.class),
            @XmlElement(name = "sequenceFlow", type = Definitions.Process.SequenceFlow.class)
        })
        protected List<Object> extensionElementsOrStartEventOrTask;
        @XmlAttribute(name = "id", required = true)
        protected String id;
        @XmlAttribute(name = "name", required = true)
        protected String name;
        @XmlAttribute(name = "isExecutable", required = true)
        protected boolean isExecutable;

        /**
         * Gets the value of the extensionElementsOrStartEventOrTask property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the extensionElementsOrStartEventOrTask property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getExtensionElementsOrStartEventOrTask().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Object }
         * {@link Definitions.Process.StartEvent }
         * {@link Definitions.Process.Task }
         * {@link Definitions.Process.SequenceFlow }
         * 
         * 
         */
        public List<Object> getExtensionElementsOrStartEventOrTask() {
            if (extensionElementsOrStartEventOrTask == null) {
                extensionElementsOrStartEventOrTask = new ArrayList<Object>();
            }
            return this.extensionElementsOrStartEventOrTask;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the isExecutable property.
         * 
         */
        public boolean isIsExecutable() {
            return isExecutable;
        }

        /**
         * Sets the value of the isExecutable property.
         * 
         */
        public void setIsExecutable(boolean value) {
            this.isExecutable = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="extensionElements">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence minOccurs="0">
         *                   &lt;element ref="{http://camunda.org/schema/zeebe/1.0}properties"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="sourceRef" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="targetRef" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "extensionElements"
        })
        public static class SequenceFlow {

            @XmlElement(required = true)
            protected Definitions.Process.SequenceFlow.ExtensionElements extensionElements;
            @XmlAttribute(name = "id", required = true)
            protected String id;
            @XmlAttribute(name = "sourceRef", required = true)
            protected String sourceRef;
            @XmlAttribute(name = "targetRef", required = true)
            protected String targetRef;
            @XmlAttribute(name = "name")
            protected String name;

            /**
             * Gets the value of the extensionElements property.
             * 
             * @return
             *     possible object is
             *     {@link Definitions.Process.SequenceFlow.ExtensionElements }
             *     
             */
            public Definitions.Process.SequenceFlow.ExtensionElements getExtensionElements() {
                return extensionElements;
            }

            /**
             * Sets the value of the extensionElements property.
             * 
             * @param value
             *     allowed object is
             *     {@link Definitions.Process.SequenceFlow.ExtensionElements }
             *     
             */
            public void setExtensionElements(Definitions.Process.SequenceFlow.ExtensionElements value) {
                this.extensionElements = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the sourceRef property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSourceRef() {
                return sourceRef;
            }

            /**
             * Sets the value of the sourceRef property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSourceRef(String value) {
                this.sourceRef = value;
            }

            /**
             * Gets the value of the targetRef property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTargetRef() {
                return targetRef;
            }

            /**
             * Sets the value of the targetRef property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTargetRef(String value) {
                this.targetRef = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence minOccurs="0">
             *         &lt;element ref="{http://camunda.org/schema/zeebe/1.0}properties"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "properties"
            })
            public static class ExtensionElements {

                @XmlElement(namespace = "http://camunda.org/schema/zeebe/1.0")
                protected Properties properties;

                /**
                 * Gets the value of the properties property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Properties }
                 *     
                 */
                public Properties getProperties() {
                    return properties;
                }

                /**
                 * Sets the value of the properties property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Properties }
                 *     
                 */
                public void setProperties(Properties value) {
                    this.properties = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="outgoing" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "outgoing"
        })
        public static class StartEvent {

            @XmlElement(required = true)
            protected String outgoing;
            @XmlAttribute(name = "id", required = true)
            protected String id;
            @XmlAttribute(name = "name", required = true)
            protected String name;

            /**
             * Gets the value of the outgoing property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOutgoing() {
                return outgoing;
            }

            /**
             * Sets the value of the outgoing property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOutgoing(String value) {
                this.outgoing = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="extensionElements">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element ref="{http://camunda.org/schema/zeebe/1.0}properties"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="incoming" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *         &lt;element name="outgoing" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "extensionElements",
            "incoming",
            "outgoing"
        })
        public static class Task {

            @XmlElement(required = true)
            protected Definitions.Process.Task.ExtensionElements extensionElements;
            @XmlElement(required = true)
            protected List<String> incoming;
            @XmlElement(required = true)
            protected List<String> outgoing;
            @XmlAttribute(name = "id", required = true)
            protected String id;
            @XmlAttribute(name = "name", required = true)
            protected String name;

            /**
             * Gets the value of the extensionElements property.
             * 
             * @return
             *     possible object is
             *     {@link Definitions.Process.Task.ExtensionElements }
             *     
             */
            public Definitions.Process.Task.ExtensionElements getExtensionElements() {
                return extensionElements;
            }

            /**
             * Sets the value of the extensionElements property.
             * 
             * @param value
             *     allowed object is
             *     {@link Definitions.Process.Task.ExtensionElements }
             *     
             */
            public void setExtensionElements(Definitions.Process.Task.ExtensionElements value) {
                this.extensionElements = value;
            }

            /**
             * Gets the value of the incoming property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the incoming property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getIncoming().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getIncoming() {
                if (incoming == null) {
                    incoming = new ArrayList<String>();
                }
                return this.incoming;
            }

            /**
             * Gets the value of the outgoing property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the outgoing property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getOutgoing().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getOutgoing() {
                if (outgoing == null) {
                    outgoing = new ArrayList<String>();
                }
                return this.outgoing;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element ref="{http://camunda.org/schema/zeebe/1.0}properties"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "properties"
            })
            public static class ExtensionElements {

                @XmlElement(namespace = "http://camunda.org/schema/zeebe/1.0", required = true)
                protected Properties properties;

                /**
                 * Gets the value of the properties property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Properties }
                 *     
                 */
                public Properties getProperties() {
                    return properties;
                }

                /**
                 * Sets the value of the properties property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Properties }
                 *     
                 */
                public void setProperties(Properties value) {
                    this.properties = value;
                }

            }

        }

    }

}
