//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.28 at 05:06:42 PM CEST 
//


package org.omg.spec.bpmn._20100524.model;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.omg.spec.bpmn._20100524.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.omg.spec.bpmn._20100524.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Definitions }
     * 
     */
    public Definitions createDefinitions() {
        return new Definitions();
    }

    /**
     * Create an instance of {@link Definitions.Process }
     * 
     */
    public Definitions.Process createDefinitionsProcess() {
        return new Definitions.Process();
    }

    /**
     * Create an instance of {@link Definitions.Process.SequenceFlow }
     * 
     */
    public Definitions.Process.SequenceFlow createDefinitionsProcessSequenceFlow() {
        return new Definitions.Process.SequenceFlow();
    }

    /**
     * Create an instance of {@link Definitions.Process.Task }
     * 
     */
    public Definitions.Process.Task createDefinitionsProcessTask() {
        return new Definitions.Process.Task();
    }

    /**
     * Create an instance of {@link Definitions.Process.StartEvent }
     * 
     */
    public Definitions.Process.StartEvent createDefinitionsProcessStartEvent() {
        return new Definitions.Process.StartEvent();
    }

    /**
     * Create an instance of {@link Definitions.Process.SequenceFlow.ExtensionElements }
     * 
     */
    public Definitions.Process.SequenceFlow.ExtensionElements createDefinitionsProcessSequenceFlowExtensionElements() {
        return new Definitions.Process.SequenceFlow.ExtensionElements();
    }

    /**
     * Create an instance of {@link Definitions.Process.Task.ExtensionElements }
     * 
     */
    public Definitions.Process.Task.ExtensionElements createDefinitionsProcessTaskExtensionElements() {
        return new Definitions.Process.Task.ExtensionElements();
    }

}
