//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.28 at 05:06:42 PM CEST 
//


package org.omg.spec.bpmn._20100524.di;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import org.omg.spec.dd._20100524.dc.Bounds;
import org.omg.spec.dd._20100524.di.Waypoint;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BPMNPlane">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="BPMNShape" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{http://www.omg.org/spec/DD/20100524/DC}Bounds"/>
 *                             &lt;element name="BPMNLabel">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence minOccurs="0">
 *                                       &lt;element ref="{http://www.omg.org/spec/DD/20100524/DC}Bounds"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="bpmnElement" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="BPMNEdge" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{http://www.omg.org/spec/DD/20100524/DI}waypoint" maxOccurs="unbounded"/>
 *                             &lt;element name="BPMNLabel" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element ref="{http://www.omg.org/spec/DD/20100524/DC}Bounds"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="bpmnElement" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="bpmnElement" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bpmnPlane"
})
@XmlRootElement(name = "BPMNDiagram")
public class BPMNDiagram {

    @XmlElement(name = "BPMNPlane", required = true)
    protected BPMNDiagram.BPMNPlane bpmnPlane;
    @XmlAttribute(name = "id", required = true)
    protected String id;

    /**
     * Gets the value of the bpmnPlane property.
     * 
     * @return
     *     possible object is
     *     {@link BPMNDiagram.BPMNPlane }
     *     
     */
    public BPMNDiagram.BPMNPlane getBPMNPlane() {
        return bpmnPlane;
    }

    /**
     * Sets the value of the bpmnPlane property.
     * 
     * @param value
     *     allowed object is
     *     {@link BPMNDiagram.BPMNPlane }
     *     
     */
    public void setBPMNPlane(BPMNDiagram.BPMNPlane value) {
        this.bpmnPlane = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="BPMNShape" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://www.omg.org/spec/DD/20100524/DC}Bounds"/>
     *                   &lt;element name="BPMNLabel">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence minOccurs="0">
     *                             &lt;element ref="{http://www.omg.org/spec/DD/20100524/DC}Bounds"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="bpmnElement" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="BPMNEdge" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://www.omg.org/spec/DD/20100524/DI}waypoint" maxOccurs="unbounded"/>
     *                   &lt;element name="BPMNLabel" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element ref="{http://www.omg.org/spec/DD/20100524/DC}Bounds"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="bpmnElement" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="bpmnElement" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bpmnShape",
        "bpmnEdge"
    })
    public static class BPMNPlane {

        @XmlElement(name = "BPMNShape", required = true)
        protected List<BPMNDiagram.BPMNPlane.BPMNShape> bpmnShape;
        @XmlElement(name = "BPMNEdge", required = true)
        protected List<BPMNDiagram.BPMNPlane.BPMNEdge> bpmnEdge;
        @XmlAttribute(name = "id", required = true)
        protected String id;
        @XmlAttribute(name = "bpmnElement", required = true)
        protected String bpmnElement;

        /**
         * Gets the value of the bpmnShape property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the bpmnShape property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBPMNShape().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BPMNDiagram.BPMNPlane.BPMNShape }
         * 
         * 
         */
        public List<BPMNDiagram.BPMNPlane.BPMNShape> getBPMNShape() {
            if (bpmnShape == null) {
                bpmnShape = new ArrayList<BPMNDiagram.BPMNPlane.BPMNShape>();
            }
            return this.bpmnShape;
        }

        /**
         * Gets the value of the bpmnEdge property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the bpmnEdge property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBPMNEdge().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BPMNDiagram.BPMNPlane.BPMNEdge }
         * 
         * 
         */
        public List<BPMNDiagram.BPMNPlane.BPMNEdge> getBPMNEdge() {
            if (bpmnEdge == null) {
                bpmnEdge = new ArrayList<BPMNDiagram.BPMNPlane.BPMNEdge>();
            }
            return this.bpmnEdge;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the bpmnElement property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBpmnElement() {
            return bpmnElement;
        }

        /**
         * Sets the value of the bpmnElement property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBpmnElement(String value) {
            this.bpmnElement = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://www.omg.org/spec/DD/20100524/DI}waypoint" maxOccurs="unbounded"/>
         *         &lt;element name="BPMNLabel" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element ref="{http://www.omg.org/spec/DD/20100524/DC}Bounds"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="bpmnElement" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "waypoint",
            "bpmnLabel"
        })
        public static class BPMNEdge {

            @XmlElement(namespace = "http://www.omg.org/spec/DD/20100524/DI", required = true)
            protected List<Waypoint> waypoint;
            @XmlElement(name = "BPMNLabel")
            protected BPMNDiagram.BPMNPlane.BPMNEdge.BPMNLabel bpmnLabel;
            @XmlAttribute(name = "id", required = true)
            protected String id;
            @XmlAttribute(name = "bpmnElement", required = true)
            protected String bpmnElement;

            /**
             * Gets the value of the waypoint property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the waypoint property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getWaypoint().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Waypoint }
             * 
             * 
             */
            public List<Waypoint> getWaypoint() {
                if (waypoint == null) {
                    waypoint = new ArrayList<Waypoint>();
                }
                return this.waypoint;
            }

            /**
             * Gets the value of the bpmnLabel property.
             * 
             * @return
             *     possible object is
             *     {@link BPMNDiagram.BPMNPlane.BPMNEdge.BPMNLabel }
             *     
             */
            public BPMNDiagram.BPMNPlane.BPMNEdge.BPMNLabel getBPMNLabel() {
                return bpmnLabel;
            }

            /**
             * Sets the value of the bpmnLabel property.
             * 
             * @param value
             *     allowed object is
             *     {@link BPMNDiagram.BPMNPlane.BPMNEdge.BPMNLabel }
             *     
             */
            public void setBPMNLabel(BPMNDiagram.BPMNPlane.BPMNEdge.BPMNLabel value) {
                this.bpmnLabel = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the bpmnElement property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBpmnElement() {
                return bpmnElement;
            }

            /**
             * Sets the value of the bpmnElement property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBpmnElement(String value) {
                this.bpmnElement = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element ref="{http://www.omg.org/spec/DD/20100524/DC}Bounds"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "bounds"
            })
            public static class BPMNLabel {

                @XmlElement(name = "Bounds", namespace = "http://www.omg.org/spec/DD/20100524/DC", required = true)
                protected Bounds bounds;

                /**
                 * Gets the value of the bounds property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Bounds }
                 *     
                 */
                public Bounds getBounds() {
                    return bounds;
                }

                /**
                 * Sets the value of the bounds property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Bounds }
                 *     
                 */
                public void setBounds(Bounds value) {
                    this.bounds = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://www.omg.org/spec/DD/20100524/DC}Bounds"/>
         *         &lt;element name="BPMNLabel">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence minOccurs="0">
         *                   &lt;element ref="{http://www.omg.org/spec/DD/20100524/DC}Bounds"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="bpmnElement" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "bounds",
            "bpmnLabel"
        })
        public static class BPMNShape {

            @XmlElement(name = "Bounds", namespace = "http://www.omg.org/spec/DD/20100524/DC", required = true)
            protected Bounds bounds;
            @XmlElement(name = "BPMNLabel", required = true)
            protected BPMNDiagram.BPMNPlane.BPMNShape.BPMNLabel bpmnLabel;
            @XmlAttribute(name = "id", required = true)
            protected String id;
            @XmlAttribute(name = "bpmnElement", required = true)
            protected String bpmnElement;

            /**
             * Gets the value of the bounds property.
             * 
             * @return
             *     possible object is
             *     {@link Bounds }
             *     
             */
            public Bounds getBounds() {
                return bounds;
            }

            /**
             * Sets the value of the bounds property.
             * 
             * @param value
             *     allowed object is
             *     {@link Bounds }
             *     
             */
            public void setBounds(Bounds value) {
                this.bounds = value;
            }

            /**
             * Gets the value of the bpmnLabel property.
             * 
             * @return
             *     possible object is
             *     {@link BPMNDiagram.BPMNPlane.BPMNShape.BPMNLabel }
             *     
             */
            public BPMNDiagram.BPMNPlane.BPMNShape.BPMNLabel getBPMNLabel() {
                return bpmnLabel;
            }

            /**
             * Sets the value of the bpmnLabel property.
             * 
             * @param value
             *     allowed object is
             *     {@link BPMNDiagram.BPMNPlane.BPMNShape.BPMNLabel }
             *     
             */
            public void setBPMNLabel(BPMNDiagram.BPMNPlane.BPMNShape.BPMNLabel value) {
                this.bpmnLabel = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the bpmnElement property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBpmnElement() {
                return bpmnElement;
            }

            /**
             * Sets the value of the bpmnElement property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBpmnElement(String value) {
                this.bpmnElement = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence minOccurs="0">
             *         &lt;element ref="{http://www.omg.org/spec/DD/20100524/DC}Bounds"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "bounds"
            })
            public static class BPMNLabel {

                @XmlElement(name = "Bounds", namespace = "http://www.omg.org/spec/DD/20100524/DC")
                protected Bounds bounds;

                /**
                 * Gets the value of the bounds property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Bounds }
                 *     
                 */
                public Bounds getBounds() {
                    return bounds;
                }

                /**
                 * Sets the value of the bounds property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Bounds }
                 *     
                 */
                public void setBounds(Bounds value) {
                    this.bounds = value;
                }

            }

        }

    }

}
